// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGf3ah-rEfa5L-WHp-mMhSp6IW9uDBBYg',
    appId: '1:530501685793:web:efd570795923ea41ea8960',
    messagingSenderId: '530501685793',
    projectId: 'bookonlinedigital',
    authDomain: 'bookonlinedigital.firebaseapp.com',
    storageBucket: 'bookonlinedigital.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Ks4aHZLUmTP0JbRW15t16m4jh5Y5V7s',
    appId: '1:530501685793:android:70193850e61a3ad8ea8960',
    messagingSenderId: '530501685793',
    projectId: 'bookonlinedigital',
    storageBucket: 'bookonlinedigital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dJHxyr_aVAkwiODHIaa9byHY6Pqn-Lw',
    appId: '1:530501685793:ios:fbf6df66bcffaec0ea8960',
    messagingSenderId: '530501685793',
    projectId: 'bookonlinedigital',
    storageBucket: 'bookonlinedigital.firebasestorage.app',
    iosBundleId: 'com.domain.bookonlinedigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6dJHxyr_aVAkwiODHIaa9byHY6Pqn-Lw',
    appId: '1:530501685793:ios:fbf6df66bcffaec0ea8960',
    messagingSenderId: '530501685793',
    projectId: 'bookonlinedigital',
    storageBucket: 'bookonlinedigital.firebasestorage.app',
    iosBundleId: 'com.domain.bookonlinedigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGf3ah-rEfa5L-WHp-mMhSp6IW9uDBBYg',
    appId: '1:530501685793:web:c3187a5ef53487caea8960',
    messagingSenderId: '530501685793',
    projectId: 'bookonlinedigital',
    authDomain: 'bookonlinedigital.firebaseapp.com',
    storageBucket: 'bookonlinedigital.firebasestorage.app',
  );
}
